package com.mycompany.myapp;






import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;
import com.codename1.ui.Image;
import com.codename1.ui.layouts.BorderLayout;
import com.mycompany.myapp.gui.AffichageEvent;
import com.mycompany.myapp.services.ServiceEvent;
import com.sun.javafx.event.EventDispatchTreeImpl;




/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;

    private Resources theme;

   ServiceEvent serv = new ServiceEvent();

    public void init(Object context) {

        //theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        //  AffichageEvent all=new AffichageEvent(serv.getList());
        //  all.getF().show();
        //Login log=new Login();
        //signin sign = new signin();
     AffichageEvent aff=new AffichageEvent(theme);
         
        ServiceEvent se=new ServiceEvent();
        // AffichageEvent aff;
        new java.util.Timer().schedule(
                new java.util.TimerTask() {
                    @Override
                    public void run() {
                        //  log.getLogin().show();
                        aff.getF().show();
                    }
                },
                4000
        );
//AfficheBonplan a = new AfficheBonplan();
//AffichageEvent a = new AffichageEvent();

//        Add a = new Add();
//a.getF().show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
